-- ============================================
-- SNOWGOAL - Gold Dynamic Tables
-- ============================================

USE ROLE SNOWGOAL_ROLE;
USE DATABASE SNOWGOAL_DB;
USE SCHEMA GOLD;

-- ----------------------------------------
-- DT_LEAGUE_STANDINGS - Live League Table
-- ----------------------------------------
CREATE OR REPLACE DYNAMIC TABLE DT_LEAGUE_STANDINGS
    TARGET_LAG = '1 hour'
    WAREHOUSE = SNOWGOAL_WH_XS
AS
SELECT
    COMPETITION_CODE,
    SEASON_YEAR,
    POSITION,
    TEAM_ID,
    TEAM_NAME,
    TEAM_TLA,
    TEAM_CREST,
    PLAYED,
    WON,
    DRAW,
    LOST,
    POINTS,
    GOALS_FOR,
    GOALS_AGAINST,
    GOAL_DIFF,
    FORM,
    -- Calculated metrics
    ROUND(POINTS / NULLIF(PLAYED, 0), 2) AS POINTS_PER_GAME,
    ROUND(GOALS_FOR / NULLIF(PLAYED, 0), 2) AS GOALS_PER_GAME,
    ROUND(GOALS_AGAINST / NULLIF(PLAYED, 0), 2) AS GOALS_CONCEDED_PER_GAME,
    ROUND(WON * 100.0 / NULLIF(PLAYED, 0), 1) AS WIN_PERCENTAGE
FROM SILVER.STANDINGS;

-- ----------------------------------------
-- DT_TOP_SCORERS - Top Scorers Leaderboard
-- ----------------------------------------
CREATE OR REPLACE DYNAMIC TABLE DT_TOP_SCORERS
    TARGET_LAG = '1 hour'
    WAREHOUSE = SNOWGOAL_WH_XS
AS
SELECT
    COMPETITION_CODE,
    SEASON_YEAR,
    PLAYER_ID,
    PLAYER_NAME,
    NATIONALITY,
    POSITION,
    DATE_OF_BIRTH,
    DATEDIFF('year', DATE_OF_BIRTH, CURRENT_DATE()) AS AGE,
    TEAM_ID,
    TEAM_NAME,
    TEAM_SHORT,
    GOALS,
    ASSISTS,
    PENALTIES,
    PLAYED_MATCHES,
    -- Calculated metrics
    GOALS + COALESCE(ASSISTS, 0) AS GOAL_CONTRIBUTIONS,
    ROUND(GOALS / NULLIF(PLAYED_MATCHES, 0), 2) AS GOALS_PER_MATCH,
    ROUND((GOALS + COALESCE(ASSISTS, 0)) / NULLIF(PLAYED_MATCHES, 0), 2) AS CONTRIBUTIONS_PER_MATCH,
    RANK() OVER (PARTITION BY COMPETITION_CODE, SEASON_YEAR ORDER BY GOALS DESC) AS GOALS_RANK,
    RANK() OVER (PARTITION BY COMPETITION_CODE, SEASON_YEAR ORDER BY GOALS + COALESCE(ASSISTS, 0) DESC) AS CONTRIBUTIONS_RANK
FROM SILVER.SCORERS;

-- ----------------------------------------
-- DT_TEAM_STATS - Team Performance Stats
-- ----------------------------------------
CREATE OR REPLACE DYNAMIC TABLE DT_TEAM_STATS
    TARGET_LAG = '1 hour'
    WAREHOUSE = SNOWGOAL_WH_XS
AS
WITH home_stats AS (
    SELECT
        COMPETITION_CODE,
        SEASON_YEAR,
        HOME_TEAM_ID AS TEAM_ID,
        HOME_TEAM_NAME AS TEAM_NAME,
        COUNT(*) AS HOME_PLAYED,
        SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS HOME_WINS,
        SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS HOME_DRAWS,
        SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS HOME_LOSSES,
        SUM(HOME_SCORE) AS HOME_GOALS_FOR,
        SUM(AWAY_SCORE) AS HOME_GOALS_AGAINST
    FROM SILVER.MATCHES
    WHERE STATUS = 'FINISHED'
    GROUP BY COMPETITION_CODE, SEASON_YEAR, HOME_TEAM_ID, HOME_TEAM_NAME
),
away_stats AS (
    SELECT
        COMPETITION_CODE,
        SEASON_YEAR,
        AWAY_TEAM_ID AS TEAM_ID,
        AWAY_TEAM_NAME AS TEAM_NAME,
        COUNT(*) AS AWAY_PLAYED,
        SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS AWAY_WINS,
        SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS AWAY_DRAWS,
        SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS AWAY_LOSSES,
        SUM(AWAY_SCORE) AS AWAY_GOALS_FOR,
        SUM(HOME_SCORE) AS AWAY_GOALS_AGAINST
    FROM SILVER.MATCHES
    WHERE STATUS = 'FINISHED'
    GROUP BY COMPETITION_CODE, SEASON_YEAR, AWAY_TEAM_ID, AWAY_TEAM_NAME
)
SELECT
    COALESCE(h.COMPETITION_CODE, a.COMPETITION_CODE) AS COMPETITION_CODE,
    COALESCE(h.SEASON_YEAR, a.SEASON_YEAR) AS SEASON_YEAR,
    COALESCE(h.TEAM_ID, a.TEAM_ID) AS TEAM_ID,
    COALESCE(h.TEAM_NAME, a.TEAM_NAME) AS TEAM_NAME,
    -- Home stats
    COALESCE(h.HOME_PLAYED, 0) AS HOME_PLAYED,
    COALESCE(h.HOME_WINS, 0) AS HOME_WINS,
    COALESCE(h.HOME_DRAWS, 0) AS HOME_DRAWS,
    COALESCE(h.HOME_LOSSES, 0) AS HOME_LOSSES,
    COALESCE(h.HOME_GOALS_FOR, 0) AS HOME_GOALS_FOR,
    COALESCE(h.HOME_GOALS_AGAINST, 0) AS HOME_GOALS_AGAINST,
    -- Away stats
    COALESCE(a.AWAY_PLAYED, 0) AS AWAY_PLAYED,
    COALESCE(a.AWAY_WINS, 0) AS AWAY_WINS,
    COALESCE(a.AWAY_DRAWS, 0) AS AWAY_DRAWS,
    COALESCE(a.AWAY_LOSSES, 0) AS AWAY_LOSSES,
    COALESCE(a.AWAY_GOALS_FOR, 0) AS AWAY_GOALS_FOR,
    COALESCE(a.AWAY_GOALS_AGAINST, 0) AS AWAY_GOALS_AGAINST,
    -- Totals
    COALESCE(h.HOME_PLAYED, 0) + COALESCE(a.AWAY_PLAYED, 0) AS TOTAL_PLAYED,
    COALESCE(h.HOME_WINS, 0) + COALESCE(a.AWAY_WINS, 0) AS TOTAL_WINS,
    COALESCE(h.HOME_GOALS_FOR, 0) + COALESCE(a.AWAY_GOALS_FOR, 0) AS TOTAL_GOALS_FOR,
    COALESCE(h.HOME_GOALS_AGAINST, 0) + COALESCE(a.AWAY_GOALS_AGAINST, 0) AS TOTAL_GOALS_AGAINST,
    -- Home/Away performance diff
    ROUND((COALESCE(h.HOME_WINS, 0) * 3 + COALESCE(h.HOME_DRAWS, 0)) / NULLIF(COALESCE(h.HOME_PLAYED, 0), 0), 2) AS HOME_PPG,
    ROUND((COALESCE(a.AWAY_WINS, 0) * 3 + COALESCE(a.AWAY_DRAWS, 0)) / NULLIF(COALESCE(a.AWAY_PLAYED, 0), 0), 2) AS AWAY_PPG
FROM home_stats h
FULL OUTER JOIN away_stats a
    ON h.TEAM_ID = a.TEAM_ID
    AND h.COMPETITION_CODE = a.COMPETITION_CODE
    AND h.SEASON_YEAR = a.SEASON_YEAR;

-- ----------------------------------------
-- DT_RECENT_MATCHES - Recent Results
-- ----------------------------------------
CREATE OR REPLACE DYNAMIC TABLE DT_RECENT_MATCHES
    TARGET_LAG = '30 minutes'
    WAREHOUSE = SNOWGOAL_WH_XS
AS
SELECT
    MATCH_ID,
    COMPETITION_CODE,
    SEASON_YEAR,
    MATCH_DATE,
    STATUS,
    MATCHDAY,
    STAGE,
    HOME_TEAM_ID,
    HOME_TEAM_NAME,
    HOME_TEAM_TLA,
    AWAY_TEAM_ID,
    AWAY_TEAM_NAME,
    AWAY_TEAM_TLA,
    HOME_SCORE,
    AWAY_SCORE,
    HOME_SCORE_HT,
    AWAY_SCORE_HT,
    WINNER,
    REFEREE_NAME,
    -- Calculated
    HOME_SCORE || ' - ' || AWAY_SCORE AS SCORE_DISPLAY,
    CASE
        WHEN WINNER = 'HOME_TEAM' THEN HOME_TEAM_TLA || ' WIN'
        WHEN WINNER = 'AWAY_TEAM' THEN AWAY_TEAM_TLA || ' WIN'
        WHEN WINNER = 'DRAW' THEN 'DRAW'
        ELSE STATUS
    END AS RESULT_DISPLAY,
    DATEDIFF('day', MATCH_DATE, CURRENT_TIMESTAMP()) AS DAYS_AGO
FROM SILVER.MATCHES
WHERE MATCH_DATE >= DATEADD('day', -30, CURRENT_DATE())
   OR STATUS IN ('SCHEDULED', 'TIMED', 'IN_PLAY', 'PAUSED');

-- ----------------------------------------
-- DT_UPCOMING_FIXTURES - Next Matches
-- ----------------------------------------
CREATE OR REPLACE DYNAMIC TABLE DT_UPCOMING_FIXTURES
    TARGET_LAG = '30 minutes'
    WAREHOUSE = SNOWGOAL_WH_XS
AS
SELECT
    MATCH_ID,
    COMPETITION_CODE,
    SEASON_YEAR,
    MATCH_DATE,
    STATUS,
    MATCHDAY,
    HOME_TEAM_ID,
    HOME_TEAM_NAME,
    HOME_TEAM_TLA,
    AWAY_TEAM_ID,
    AWAY_TEAM_NAME,
    AWAY_TEAM_TLA,
    -- Time until match
    DATEDIFF('hour', CURRENT_TIMESTAMP(), MATCH_DATE) AS HOURS_UNTIL,
    DATEDIFF('day', CURRENT_DATE(), MATCH_DATE::DATE) AS DAYS_UNTIL,
    -- Formatted display
    TO_CHAR(MATCH_DATE, 'DY DD MON HH24:MI') AS MATCH_DATETIME_DISPLAY
FROM SILVER.MATCHES
WHERE STATUS IN ('SCHEDULED', 'TIMED')
  AND MATCH_DATE > CURRENT_TIMESTAMP()
ORDER BY MATCH_DATE;

-- Verify
SHOW DYNAMIC TABLES IN SCHEMA GOLD;
