USE ROLE SNOWGOAL_ROLE;
USE WAREHOUSE SNOWGOAL_WH_XS;
USE DATABASE SNOWGOAL_DB;
USE SCHEMA GOLD;

-- 1. LEAGUE_STANDINGS
CREATE OR REPLACE TABLE LEAGUE_STANDINGS AS
SELECT
    COMPETITION_CODE,
    SEASON_YEAR,
    POSITION,
    TEAM_ID,
    TEAM_NAME,
    TEAM_TLA,
    TEAM_CREST,
    PLAYED,
    WON,
    DRAW,
    LOST,
    POINTS,
    GOALS_FOR,
    GOALS_AGAINST,
    GOAL_DIFF,
    FORM,
    ROUND(POINTS / NULLIF(PLAYED, 0), 2) AS POINTS_PER_GAME,
    ROUND(GOALS_FOR / NULLIF(PLAYED, 0), 2) AS GOALS_PER_GAME,
    ROUND(GOALS_AGAINST / NULLIF(PLAYED, 0), 2) AS GOALS_CONCEDED_PER_GAME,
    ROUND(WON * 100.0 / NULLIF(PLAYED, 0), 1) AS WIN_PERCENTAGE
FROM SILVER.STANDINGS;

-- 2. TOP_SCORERS
CREATE OR REPLACE TABLE TOP_SCORERS AS
SELECT
    COMPETITION_CODE,
    SEASON_YEAR,
    PLAYER_ID,
    PLAYER_NAME,
    NATIONALITY,
    POSITION,
    DATE_OF_BIRTH,
    DATEDIFF('year', DATE_OF_BIRTH, CURRENT_DATE()) AS AGE,
    TEAM_ID,
    TEAM_NAME,
    TEAM_SHORT,
    GOALS,
    ASSISTS,
    PENALTIES,
    PLAYED_MATCHES,
    GOALS + COALESCE(ASSISTS, 0) AS GOAL_CONTRIBUTIONS,
    ROUND(GOALS / NULLIF(PLAYED_MATCHES, 0), 2) AS GOALS_PER_MATCH,
    ROUND((GOALS + COALESCE(ASSISTS, 0)) / NULLIF(PLAYED_MATCHES, 0), 2) AS CONTRIBUTIONS_PER_MATCH,
    RANK() OVER (PARTITION BY COMPETITION_CODE, SEASON_YEAR ORDER BY GOALS DESC) AS GOALS_RANK,
    RANK() OVER (PARTITION BY COMPETITION_CODE, SEASON_YEAR ORDER BY GOALS + COALESCE(ASSISTS, 0) DESC) AS CONTRIBUTIONS_RANK
FROM SILVER.SCORERS;

-- 3. TEAM_STATS
CREATE OR REPLACE TABLE TEAM_STATS AS
WITH home_stats AS (
    SELECT
        COMPETITION_CODE,
        SEASON_YEAR,
        HOME_TEAM_ID AS TEAM_ID,
        HOME_TEAM_NAME AS TEAM_NAME,
        COUNT(*) AS HOME_PLAYED,
        SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS HOME_WINS,
        SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS HOME_DRAWS,
        SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS HOME_LOSSES,
        SUM(HOME_SCORE) AS HOME_GOALS_FOR,
        SUM(AWAY_SCORE) AS HOME_GOALS_AGAINST
    FROM SILVER.MATCHES
    WHERE STATUS = 'FINISHED'
    GROUP BY COMPETITION_CODE, SEASON_YEAR, HOME_TEAM_ID, HOME_TEAM_NAME
),
away_stats AS (
    SELECT
        COMPETITION_CODE,
        SEASON_YEAR,
        AWAY_TEAM_ID AS TEAM_ID,
        AWAY_TEAM_NAME AS TEAM_NAME,
        COUNT(*) AS AWAY_PLAYED,
        SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS AWAY_WINS,
        SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS AWAY_DRAWS,
        SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS AWAY_LOSSES,
        SUM(AWAY_SCORE) AS AWAY_GOALS_FOR,
        SUM(HOME_SCORE) AS AWAY_GOALS_AGAINST
    FROM SILVER.MATCHES
    WHERE STATUS = 'FINISHED'
    GROUP BY COMPETITION_CODE, SEASON_YEAR, AWAY_TEAM_ID, AWAY_TEAM_NAME
)
SELECT
    COALESCE(h.COMPETITION_CODE, a.COMPETITION_CODE) AS COMPETITION_CODE,
    COALESCE(h.SEASON_YEAR, a.SEASON_YEAR) AS SEASON_YEAR,
    COALESCE(h.TEAM_ID, a.TEAM_ID) AS TEAM_ID,
    COALESCE(h.TEAM_NAME, a.TEAM_NAME) AS TEAM_NAME,
    COALESCE(h.HOME_PLAYED, 0) AS HOME_PLAYED,
    COALESCE(h.HOME_WINS, 0) AS HOME_WINS,
    COALESCE(h.HOME_DRAWS, 0) AS HOME_DRAWS,
    COALESCE(h.HOME_LOSSES, 0) AS HOME_LOSSES,
    COALESCE(h.HOME_GOALS_FOR, 0) AS HOME_GOALS_FOR,
    COALESCE(h.HOME_GOALS_AGAINST, 0) AS HOME_GOALS_AGAINST,
    COALESCE(a.AWAY_PLAYED, 0) AS AWAY_PLAYED,
    COALESCE(a.AWAY_WINS, 0) AS AWAY_WINS,
    COALESCE(a.AWAY_DRAWS, 0) AS AWAY_DRAWS,
    COALESCE(a.AWAY_LOSSES, 0) AS AWAY_LOSSES,
    COALESCE(a.AWAY_GOALS_FOR, 0) AS AWAY_GOALS_FOR,
    COALESCE(a.AWAY_GOALS_AGAINST, 0) AS AWAY_GOALS_AGAINST,
    COALESCE(h.HOME_PLAYED, 0) + COALESCE(a.AWAY_PLAYED, 0) AS TOTAL_PLAYED,
    COALESCE(h.HOME_WINS, 0) + COALESCE(a.AWAY_WINS, 0) AS TOTAL_WINS,
    COALESCE(h.HOME_GOALS_FOR, 0) + COALESCE(a.AWAY_GOALS_FOR, 0) AS TOTAL_GOALS_FOR,
    COALESCE(h.HOME_GOALS_AGAINST, 0) + COALESCE(a.AWAY_GOALS_AGAINST, 0) AS TOTAL_GOALS_AGAINST,
    ROUND((COALESCE(h.HOME_WINS, 0) * 3 + COALESCE(h.HOME_DRAWS, 0)) / NULLIF(COALESCE(h.HOME_PLAYED, 0), 0), 2) AS HOME_PPG,
    ROUND((COALESCE(a.AWAY_WINS, 0) * 3 + COALESCE(a.AWAY_DRAWS, 0)) / NULLIF(COALESCE(a.AWAY_PLAYED, 0), 0), 2) AS AWAY_PPG
FROM home_stats h
FULL OUTER JOIN away_stats a
    ON h.TEAM_ID = a.TEAM_ID
    AND h.COMPETITION_CODE = a.COMPETITION_CODE
    AND h.SEASON_YEAR = a.SEASON_YEAR;

-- 4. RECENT_MATCHES
CREATE OR REPLACE TABLE RECENT_MATCHES AS
SELECT
    MATCH_ID,
    COMPETITION_CODE,
    SEASON_YEAR,
    MATCH_DATE,
    STATUS,
    MATCHDAY,
    STAGE,
    HOME_TEAM_ID,
    HOME_TEAM_NAME,
    HOME_TEAM_TLA,
    AWAY_TEAM_ID,
    AWAY_TEAM_NAME,
    AWAY_TEAM_TLA,
    HOME_SCORE,
    AWAY_SCORE,
    HOME_SCORE_HT,
    AWAY_SCORE_HT,
    WINNER,
    REFEREE_NAME,
    HOME_SCORE || ' - ' || AWAY_SCORE AS SCORE_DISPLAY,
    CASE
        WHEN WINNER = 'HOME_TEAM' THEN HOME_TEAM_TLA || ' WIN'
        WHEN WINNER = 'AWAY_TEAM' THEN AWAY_TEAM_TLA || ' WIN'
        WHEN WINNER = 'DRAW' THEN 'DRAW'
        ELSE STATUS
    END AS RESULT_DISPLAY,
    DATEDIFF('day', MATCH_DATE, CURRENT_TIMESTAMP()) AS DAYS_AGO,
    TO_CHAR(MATCH_DATE, 'DY DD MON HH24:MI') AS MATCH_DATETIME_DISPLAY
FROM SILVER.MATCHES
WHERE MATCH_DATE >= DATEADD('day', -30, CURRENT_DATE())
   OR STATUS IN ('SCHEDULED', 'TIMED', 'IN_PLAY', 'PAUSED');

-- 5. UPCOMING_FIXTURES
CREATE OR REPLACE TABLE UPCOMING_FIXTURES AS
SELECT
    MATCH_ID,
    COMPETITION_CODE,
    SEASON_YEAR,
    MATCH_DATE,
    STATUS,
    MATCHDAY,
    HOME_TEAM_ID,
    HOME_TEAM_NAME,
    HOME_TEAM_TLA,
    AWAY_TEAM_ID,
    AWAY_TEAM_NAME,
    AWAY_TEAM_TLA,
    DATEDIFF('hour', CURRENT_TIMESTAMP(), MATCH_DATE) AS HOURS_UNTIL,
    DATEDIFF('day', CURRENT_DATE(), MATCH_DATE::DATE) AS DAYS_UNTIL,
    TO_CHAR(MATCH_DATE, 'DY DD MON HH24:MI') AS MATCH_DATETIME_DISPLAY
FROM SILVER.MATCHES
WHERE STATUS IN ('SCHEDULED', 'TIMED')
  AND MATCH_DATE > CURRENT_TIMESTAMP()
ORDER BY MATCH_DATE;

-- ============================================
-- ANALYTICS TABLES (using 8 new enrichment columns)
-- ============================================

-- 6. MATCH_PATTERNS - Time and day patterns
CREATE OR REPLACE TABLE MATCH_PATTERNS AS
SELECT
    COMPETITION_CODE,
    DAY_OF_WEEK,
    MATCH_HOUR,
    COUNT(*) AS TOTAL_MATCHES,
    ROUND(AVG(HOME_SCORE + AWAY_SCORE), 2) AS AVG_TOTAL_GOALS,
    ROUND(AVG(HOME_SCORE), 2) AS AVG_HOME_GOALS,
    ROUND(AVG(AWAY_SCORE), 2) AS AVG_AWAY_GOALS,
    SUM(CASE WHEN MATCH_DURATION != 'REGULAR' THEN 1 ELSE 0 END) AS EXTRA_TIME_MATCHES,
    SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS HOME_WINS,
    SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS AWAY_WINS,
    SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS DRAWS
FROM SILVER.MATCHES
WHERE STATUS = 'FINISHED'
  AND DAY_OF_WEEK IS NOT NULL
  AND MATCH_HOUR IS NOT NULL
GROUP BY COMPETITION_CODE, DAY_OF_WEEK, MATCH_HOUR;

-- 7. REFEREE_STATS - Referee statistics
CREATE OR REPLACE TABLE REFEREE_STATS AS
SELECT
    REFEREE_NAME,
    REFEREE_NATIONALITY,
    REFEREE_ID,
    COUNT(*) AS MATCHES_REFEREED,
    COUNT(DISTINCT COMPETITION_CODE) AS COMPETITIONS,
    COUNT(DISTINCT SEASON_YEAR) AS SEASONS,
    ROUND(AVG(HOME_SCORE + AWAY_SCORE), 2) AS AVG_GOALS_PER_MATCH,
    SUM(CASE WHEN MATCH_DURATION != 'REGULAR' THEN 1 ELSE 0 END) AS EXTRA_TIME_MATCHES,
    ROUND(100.0 * SUM(CASE WHEN MATCH_DURATION != 'REGULAR' THEN 1 ELSE 0 END) / COUNT(*), 1) AS EXTRA_TIME_PCT
FROM SILVER.MATCHES
WHERE STATUS = 'FINISHED'
  AND REFEREE_NAME IS NOT NULL
GROUP BY REFEREE_NAME, REFEREE_NATIONALITY, REFEREE_ID
ORDER BY MATCHES_REFEREED DESC;

-- 8. GEOGRAPHIC_STATS - Area/Country statistics
CREATE OR REPLACE TABLE GEOGRAPHIC_STATS AS
SELECT
    AREA_NAME,
    AREA_CODE,
    COUNT(DISTINCT COMPETITION_CODE) AS COMPETITIONS,
    COUNT(*) AS TOTAL_MATCHES,
    ROUND(AVG(HOME_SCORE + AWAY_SCORE), 2) AS AVG_GOALS_PER_MATCH,
    SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS HOME_WINS,
    SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS AWAY_WINS,
    SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS DRAWS,
    ROUND(100.0 * SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) / COUNT(*), 1) AS HOME_WIN_PCT
FROM SILVER.MATCHES
WHERE STATUS = 'FINISHED'
  AND AREA_NAME IS NOT NULL
GROUP BY AREA_NAME, AREA_CODE
ORDER BY TOTAL_MATCHES DESC;

-- 9. ODDS_ANALYSIS - Average odds and best value by match
CREATE OR REPLACE TABLE ODDS_ANALYSIS AS
SELECT
    o.GAME_ID,
    o.COMPETITION_CODE,
    o.COMMENCE_TIME,
    o.HOME_TEAM,
    o.AWAY_TEAM,
    COUNT(DISTINCT o.BOOKMAKER_KEY) AS NB_BOOKMAKERS,
    -- Average odds across all bookmakers
    ROUND(AVG(o.HOME_ODDS), 2) AS AVG_HOME_ODDS,
    ROUND(AVG(o.DRAW_ODDS), 2) AS AVG_DRAW_ODDS,
    ROUND(AVG(o.AWAY_ODDS), 2) AS AVG_AWAY_ODDS,
    -- Best odds (highest)
    MAX(o.HOME_ODDS) AS BEST_HOME_ODDS,
    MAX(o.DRAW_ODDS) AS BEST_DRAW_ODDS,
    MAX(o.AWAY_ODDS) AS BEST_AWAY_ODDS,
    -- Implied probabilities (inverse of average odds)
    ROUND(1 / AVG(o.HOME_ODDS) * 100, 1) AS IMPLIED_HOME_PROB,
    ROUND(1 / AVG(o.DRAW_ODDS) * 100, 1) AS IMPLIED_DRAW_PROB,
    ROUND(1 / AVG(o.AWAY_ODDS) * 100, 1) AS IMPLIED_AWAY_PROB,
    -- Bookmaker margin (sum of implied probs - 100)
    ROUND((1/AVG(o.HOME_ODDS) + 1/AVG(o.DRAW_ODDS) + 1/AVG(o.AWAY_ODDS) - 1) * 100, 2) AS BOOKMAKER_MARGIN_PCT,
    MAX(o.LAST_UPDATE) AS LAST_ODDS_UPDATE
FROM SILVER.ODDS o
GROUP BY o.GAME_ID, o.COMPETITION_CODE, o.COMMENCE_TIME, o.HOME_TEAM, o.AWAY_TEAM
ORDER BY o.COMMENCE_TIME DESC;