USE ROLE SNOWGOAL_ROLE;
USE WAREHOUSE SNOWGOAL_WH_XS;
USE DATABASE SNOWGOAL_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE VIEW GOLD.DATA_QUALITY_DASHBOARD AS
-- 1. Vérification des doublons
SELECT 'SILVER.MATCHES' AS TABLE_NAME, 'Duplicate Match IDs' AS CHECK_NAME, COUNT(*) AS ANOMALY_COUNT
FROM (SELECT MATCH_ID FROM SILVER.MATCHES GROUP BY MATCH_ID HAVING COUNT(*) > 1)

UNION ALL

-- 2. Vérification des scores aberrants
SELECT 'SILVER.MATCHES', 'Negative Scores (Data Error)', COUNT(*)
FROM SILVER.MATCHES WHERE HOME_SCORE < 0 OR AWAY_SCORE < 0

UNION ALL

-- 3. Vérification de cohérence
SELECT 'SILVER.MATCHES', 'Identical Teams (Home = Away)', COUNT(*)
FROM SILVER.MATCHES WHERE HOME_TEAM_ID = AWAY_TEAM_ID

UNION ALL

-- 4. Vérification des cotes (Correction ici : HOME_ODDS et AWAY_ODDS)
SELECT 'SILVER.ODDS', 'Invalid Odds (<= 1.0)', COUNT(*)
FROM SILVER.ODDS WHERE HOME_ODDS <= 1 OR DRAW_ODDS <= 1 OR AWAY_ODDS <= 1

UNION ALL

-- 5. Vérification des points au classement
SELECT 'SILVER.STANDINGS', 'Inconsistent Points Calculation', COUNT(*)
FROM SILVER.STANDINGS WHERE (WON * 3 + DRAW) != POINTS;