-- ============================================
-- SNOWGOAL - GOLD Match Analytics
-- ============================================
USE ROLE SNOWGOAL_ROLE;
USE WAREHOUSE SNOWGOAL_WH_XS;
USE DATABASE SNOWGOAL_DB;
USE SCHEMA GOLD;

-- ----------------------------------------
-- MATCH_PATTERNS - Time and day patterns
-- ----------------------------------------
CREATE OR REPLACE TABLE MATCH_PATTERNS AS
SELECT
    COMPETITION_CODE,
    DAY_OF_WEEK,
    MATCH_HOUR,
    COUNT(*) AS TOTAL_MATCHES,
    ROUND(AVG(HOME_SCORE + AWAY_SCORE), 2) AS AVG_TOTAL_GOALS,
    ROUND(AVG(HOME_SCORE), 2) AS AVG_HOME_GOALS,
    ROUND(AVG(AWAY_SCORE), 2) AS AVG_AWAY_GOALS,
    SUM(CASE WHEN MATCH_DURATION != 'REGULAR' THEN 1 ELSE 0 END) AS EXTRA_TIME_MATCHES,
    SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS HOME_WINS,
    SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS AWAY_WINS,
    SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS DRAWS
FROM SILVER.MATCHES
WHERE STATUS = 'FINISHED'
  AND DAY_OF_WEEK IS NOT NULL
  AND MATCH_HOUR IS NOT NULL
GROUP BY COMPETITION_CODE, DAY_OF_WEEK, MATCH_HOUR;

-- ----------------------------------------
-- REFEREE_STATS - Referee statistics
-- ----------------------------------------
CREATE OR REPLACE TABLE REFEREE_STATS AS
SELECT
    REFEREE_NAME,
    REFEREE_NATIONALITY,
    REFEREE_ID,
    COUNT(*) AS MATCHES_REFEREED,
    COUNT(DISTINCT COMPETITION_CODE) AS COMPETITIONS,
    COUNT(DISTINCT SEASON_YEAR) AS SEASONS,
    ROUND(AVG(HOME_SCORE + AWAY_SCORE), 2) AS AVG_GOALS_PER_MATCH,
    SUM(CASE WHEN MATCH_DURATION != 'REGULAR' THEN 1 ELSE 0 END) AS EXTRA_TIME_MATCHES,
    ROUND(100.0 * SUM(CASE WHEN MATCH_DURATION != 'REGULAR' THEN 1 ELSE 0 END) / COUNT(*), 1) AS EXTRA_TIME_PCT
FROM SILVER.MATCHES
WHERE STATUS = 'FINISHED'
  AND REFEREE_NAME IS NOT NULL
GROUP BY REFEREE_NAME, REFEREE_NATIONALITY, REFEREE_ID
ORDER BY MATCHES_REFEREED DESC;

-- ----------------------------------------
-- GEOGRAPHIC_STATS - Area/Country statistics
-- ----------------------------------------
CREATE OR REPLACE TABLE GEOGRAPHIC_STATS AS
SELECT
    AREA_NAME,
    AREA_CODE,
    COUNT(DISTINCT COMPETITION_CODE) AS COMPETITIONS,
    COUNT(*) AS TOTAL_MATCHES,
    ROUND(AVG(HOME_SCORE + AWAY_SCORE), 2) AS AVG_GOALS_PER_MATCH,
    SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS HOME_WINS,
    SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS AWAY_WINS,
    SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS DRAWS,
    ROUND(100.0 * SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) / COUNT(*), 1) AS HOME_WIN_PCT
FROM SILVER.MATCHES
WHERE STATUS = 'FINISHED'
  AND AREA_NAME IS NOT NULL
GROUP BY AREA_NAME, AREA_CODE
ORDER BY TOTAL_MATCHES DESC;

-- Verify tables created
SHOW TABLES IN SCHEMA GOLD;

-- Check row counts
SELECT 'MATCH_PATTERNS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM MATCH_PATTERNS
UNION ALL SELECT 'REFEREE_STATS', COUNT(*) FROM REFEREE_STATS
UNION ALL SELECT 'GEOGRAPHIC_STATS', COUNT(*) FROM GEOGRAPHIC_STATS;
