-- ============================================
-- SNOWGOAL - Security (RBAC & Masking Policies)
-- ============================================

USE DATABASE SNOWGOAL_DB;

-- ----------------------------------------
-- ROLES HIERARCHY
-- ----------------------------------------
-- ACCOUNTADMIN
--     └── SNOWGOAL_ADMIN
--             ├── SNOWGOAL_ANALYST (read Gold + Silver)
--             └── SNOWGOAL_VIEWER (read Gold only)

-- Create roles
CREATE ROLE IF NOT EXISTS SNOWGOAL_ADMIN
    COMMENT = 'Full access to SnowGoal database';

CREATE ROLE IF NOT EXISTS SNOWGOAL_ANALYST
    COMMENT = 'Read access to Silver and Gold schemas';

CREATE ROLE IF NOT EXISTS SNOWGOAL_VIEWER
    COMMENT = 'Read access to Gold schema only';

-- Role hierarchy
GRANT ROLE SNOWGOAL_ANALYST TO ROLE SNOWGOAL_ADMIN;
GRANT ROLE SNOWGOAL_VIEWER TO ROLE SNOWGOAL_ANALYST;

-- ----------------------------------------
-- GRANTS - ADMIN
-- ----------------------------------------
GRANT ALL ON DATABASE SNOWGOAL_DB TO ROLE SNOWGOAL_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE SNOWGOAL_DB TO ROLE SNOWGOAL_ADMIN;
GRANT ALL ON ALL TABLES IN DATABASE SNOWGOAL_DB TO ROLE SNOWGOAL_ADMIN;
GRANT ALL ON ALL VIEWS IN DATABASE SNOWGOAL_DB TO ROLE SNOWGOAL_ADMIN;
GRANT ALL ON ALL DYNAMIC TABLES IN DATABASE SNOWGOAL_DB TO ROLE SNOWGOAL_ADMIN;
GRANT USAGE ON WAREHOUSE SNOWGOAL_WH TO ROLE SNOWGOAL_ADMIN;

-- ----------------------------------------
-- GRANTS - ANALYST
-- ----------------------------------------
GRANT USAGE ON DATABASE SNOWGOAL_DB TO ROLE SNOWGOAL_ANALYST;
GRANT USAGE ON SCHEMA SILVER TO ROLE SNOWGOAL_ANALYST;
GRANT USAGE ON SCHEMA GOLD TO ROLE SNOWGOAL_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SILVER TO ROLE SNOWGOAL_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA GOLD TO ROLE SNOWGOAL_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA GOLD TO ROLE SNOWGOAL_ANALYST;
GRANT USAGE ON WAREHOUSE SNOWGOAL_WH TO ROLE SNOWGOAL_ANALYST;

-- Future grants for ANALYST
GRANT SELECT ON FUTURE TABLES IN SCHEMA SILVER TO ROLE SNOWGOAL_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOLD TO ROLE SNOWGOAL_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA GOLD TO ROLE SNOWGOAL_ANALYST;

-- ----------------------------------------
-- GRANTS - VIEWER
-- ----------------------------------------
GRANT USAGE ON DATABASE SNOWGOAL_DB TO ROLE SNOWGOAL_VIEWER;
GRANT USAGE ON SCHEMA GOLD TO ROLE SNOWGOAL_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA GOLD TO ROLE SNOWGOAL_VIEWER;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA GOLD TO ROLE SNOWGOAL_VIEWER;
GRANT USAGE ON WAREHOUSE SNOWGOAL_WH TO ROLE SNOWGOAL_VIEWER;

-- Future grants for VIEWER
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOLD TO ROLE SNOWGOAL_VIEWER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA GOLD TO ROLE SNOWGOAL_VIEWER;

-- ----------------------------------------
-- MASKING POLICY (Example: Mask player DOB)
-- ----------------------------------------
CREATE OR REPLACE MASKING POLICY MASK_DATE_OF_BIRTH
AS (val DATE) RETURNS DATE ->
    CASE
        WHEN CURRENT_ROLE() IN ('SNOWGOAL_ADMIN', 'SNOWGOAL_ANALYST') THEN val
        ELSE DATE_TRUNC('YEAR', val)  -- Viewers only see year
    END;

-- Apply masking policy to SCORERS table
ALTER TABLE SILVER.SCORERS
    MODIFY COLUMN DATE_OF_BIRTH
    SET MASKING POLICY MASK_DATE_OF_BIRTH;

-- ----------------------------------------
-- ROW ACCESS POLICY (Example: Limit by competition)
-- ----------------------------------------
-- This is optional - demonstrates row-level security

-- CREATE OR REPLACE ROW ACCESS POLICY COMPETITION_ACCESS
-- AS (competition_code VARCHAR) RETURNS BOOLEAN ->
--     CASE
--         WHEN CURRENT_ROLE() = 'SNOWGOAL_ADMIN' THEN TRUE
--         WHEN CURRENT_ROLE() = 'SNOWGOAL_ANALYST' THEN TRUE
--         WHEN CURRENT_ROLE() = 'SNOWGOAL_VIEWER' AND competition_code = 'PL' THEN TRUE
--         ELSE FALSE
--     END;

-- Verify
SHOW ROLES LIKE 'SNOWGOAL%';
SHOW GRANTS TO ROLE SNOWGOAL_ADMIN;
SHOW GRANTS TO ROLE SNOWGOAL_ANALYST;
SHOW GRANTS TO ROLE SNOWGOAL_VIEWER;
