USE ROLE SNOWGOAL_ROLE;
USE WAREHOUSE SNOWGOAL_WH_XS;
USE DATABASE SNOWGOAL_DB;

USE SCHEMA COMMON;

CREATE OR REPLACE PROCEDURE FETCH_ALL_LEAGUES()
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python', 'requests')
IMPORTS = ('@SNOWGOAL_DB.RAW.PYTHON_CODE/fetch_all_leagues.py')
HANDLER = 'fetch_all_leagues.main'
EXTERNAL_ACCESS_INTEGRATIONS = (FOOTBALL_API_ACCESS)
SECRETS = ('api_key' = SNOWGOAL_DB.COMMON.FOOTBALL_API_KEY)
COMMENT = 'Fetches data for 12 competitions with 60s delay between each';