-- ============================================
-- SNOWGOAL - Tasks (Orchestration DAG)
-- ============================================

USE ROLE SNOWGOAL_ROLE;
USE WAREHOUSE SNOWGOAL_WH_XS;
USE DATABASE SNOWGOAL_DB;
USE SCHEMA COMMON;

-- ----------------------------------------
-- TASK 1: Fetch all leagues from API
-- Runs 3x daily: 7h, 17h, 00h (Europe/Paris)
-- ----------------------------------------
CREATE OR REPLACE TASK TASK_FETCH_ALL_LEAGUES
    WAREHOUSE = SNOWGOAL_WH_XS
    SCHEDULE = 'USING CRON 0 7,17,0 * * * Europe/Paris'
    COMMENT = 'Fetch data for all 5 European leagues from football-data.org (7h, 17h, 00h)'
AS
CALL FETCH_ALL_LEAGUES();

-- ----------------------------------------
-- TASK 2: Fetch betting odds
-- Runs after leagues fetch completes
-- ----------------------------------------
CREATE OR REPLACE TASK TASK_FETCH_ODDS
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_FETCH_ALL_LEAGUES
AS
CALL FETCH_ODDS();

-- ----------------------------------------
-- TASK 3: Merge to Silver
-- Runs after odds fetch completes
-- ----------------------------------------
CREATE OR REPLACE TASK TASK_MERGE_TO_SILVER
  WAREHOUSE = SNOWGOAL_WH_XS
  AFTER TASK_FETCH_ODDS
AS
CALL SP_MERGE_TO_SILVER();

-- Task 5: Refresh TEAM_STATS
CREATE OR REPLACE TASK TASK_REFRESH_TEAM_STATS
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.TEAM_STATS
WITH home_stats AS (
    SELECT
        COMPETITION_CODE,
        SEASON_YEAR,
        HOME_TEAM_ID AS TEAM_ID,
        HOME_TEAM_NAME AS TEAM_NAME,
        COUNT(*) AS HOME_PLAYED,
        SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS HOME_WINS,
        SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS HOME_DRAWS,
        SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS HOME_LOSSES,
        SUM(HOME_SCORE) AS HOME_GOALS_FOR,
        SUM(AWAY_SCORE) AS HOME_GOALS_AGAINST
    FROM SILVER.MATCHES
    WHERE STATUS = 'FINISHED'
    GROUP BY COMPETITION_CODE, SEASON_YEAR, HOME_TEAM_ID, HOME_TEAM_NAME
),
away_stats AS (
    SELECT
        COMPETITION_CODE,
        SEASON_YEAR,
        AWAY_TEAM_ID AS TEAM_ID,
        AWAY_TEAM_NAME AS TEAM_NAME,
        COUNT(*) AS AWAY_PLAYED,
        SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS AWAY_WINS,
        SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS AWAY_DRAWS,
        SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS AWAY_LOSSES,
        SUM(AWAY_SCORE) AS AWAY_GOALS_FOR,
        SUM(HOME_SCORE) AS AWAY_GOALS_AGAINST
    FROM SILVER.MATCHES
    WHERE STATUS = 'FINISHED'
    GROUP BY COMPETITION_CODE, SEASON_YEAR, AWAY_TEAM_ID, AWAY_TEAM_NAME
)
SELECT
    COALESCE(h.COMPETITION_CODE, a.COMPETITION_CODE) AS COMPETITION_CODE,
    COALESCE(h.SEASON_YEAR, a.SEASON_YEAR) AS SEASON_YEAR,
    COALESCE(h.TEAM_ID, a.TEAM_ID) AS TEAM_ID,
    COALESCE(h.TEAM_NAME, a.TEAM_NAME) AS TEAM_NAME,
    COALESCE(h.HOME_PLAYED, 0) AS HOME_PLAYED,
    COALESCE(h.HOME_WINS, 0) AS HOME_WINS,
    COALESCE(h.HOME_DRAWS, 0) AS HOME_DRAWS,
    COALESCE(h.HOME_LOSSES, 0) AS HOME_LOSSES,
    COALESCE(h.HOME_GOALS_FOR, 0) AS HOME_GOALS_FOR,
    COALESCE(h.HOME_GOALS_AGAINST, 0) AS HOME_GOALS_AGAINST,
    COALESCE(a.AWAY_PLAYED, 0) AS AWAY_PLAYED,
    COALESCE(a.AWAY_WINS, 0) AS AWAY_WINS,
    COALESCE(a.AWAY_DRAWS, 0) AS AWAY_DRAWS,
    COALESCE(a.AWAY_LOSSES, 0) AS AWAY_LOSSES,
    COALESCE(a.AWAY_GOALS_FOR, 0) AS AWAY_GOALS_FOR,
    COALESCE(a.AWAY_GOALS_AGAINST, 0) AS AWAY_GOALS_AGAINST,
    COALESCE(h.HOME_PLAYED, 0) + COALESCE(a.AWAY_PLAYED, 0) AS TOTAL_PLAYED,
    COALESCE(h.HOME_WINS, 0) + COALESCE(a.AWAY_WINS, 0) AS TOTAL_WINS,
    COALESCE(h.HOME_GOALS_FOR, 0) + COALESCE(a.AWAY_GOALS_FOR, 0) AS TOTAL_GOALS_FOR,
    COALESCE(h.HOME_GOALS_AGAINST, 0) + COALESCE(a.AWAY_GOALS_AGAINST, 0) AS TOTAL_GOALS_AGAINST,
    ROUND((COALESCE(h.HOME_WINS, 0) * 3 + COALESCE(h.HOME_DRAWS, 0)) / NULLIF(COALESCE(h.HOME_PLAYED, 0), 0), 2) AS HOME_PPG,
    ROUND((COALESCE(a.AWAY_WINS, 0) * 3 + COALESCE(a.AWAY_DRAWS, 0)) / NULLIF(COALESCE(a.AWAY_PLAYED, 0), 0), 2) AS AWAY_PPG
FROM home_stats h
FULL OUTER JOIN away_stats a
    ON h.TEAM_ID = a.TEAM_ID
    AND h.COMPETITION_CODE = a.COMPETITION_CODE
    AND h.SEASON_YEAR = a.SEASON_YEAR;

-- Task 6: Refresh RECENT_MATCHES
CREATE OR REPLACE TASK TASK_REFRESH_RECENT_MATCHES
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.RECENT_MATCHES
SELECT
    MATCH_ID,
    COMPETITION_CODE,
    SEASON_YEAR,
    MATCH_DATE,
    STATUS,
    MATCHDAY,
    STAGE,
    HOME_TEAM_ID,
    HOME_TEAM_NAME,
    HOME_TEAM_TLA,
    AWAY_TEAM_ID,
    AWAY_TEAM_NAME,
    AWAY_TEAM_TLA,
    HOME_SCORE,
    AWAY_SCORE,
    HOME_SCORE_HT,
    AWAY_SCORE_HT,
    WINNER,
    REFEREE_NAME,
    HOME_SCORE || ' - ' || AWAY_SCORE AS SCORE_DISPLAY,
    CASE
        WHEN WINNER = 'HOME_TEAM' THEN HOME_TEAM_TLA || ' WIN'
        WHEN WINNER = 'AWAY_TEAM' THEN AWAY_TEAM_TLA || ' WIN'
        WHEN WINNER = 'DRAW' THEN 'DRAW'
        ELSE STATUS
    END AS RESULT_DISPLAY,
    DATEDIFF('day', MATCH_DATE, CURRENT_TIMESTAMP()) AS DAYS_AGO
FROM SILVER.MATCHES
WHERE MATCH_DATE >= DATEADD('day', -30, CURRENT_DATE())
   OR STATUS IN ('SCHEDULED', 'TIMED', 'IN_PLAY', 'PAUSED');

-- Task 7: Refresh UPCOMING_FIXTURES
CREATE OR REPLACE TASK TASK_REFRESH_UPCOMING_FIXTURES
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.UPCOMING_FIXTURES
SELECT
    MATCH_ID,
    COMPETITION_CODE,
    SEASON_YEAR,
    MATCH_DATE,
    STATUS,
    MATCHDAY,
    HOME_TEAM_ID,
    HOME_TEAM_NAME,
    HOME_TEAM_TLA,
    AWAY_TEAM_ID,
    AWAY_TEAM_NAME,
    AWAY_TEAM_TLA,
    DATEDIFF('hour', CURRENT_TIMESTAMP(), MATCH_DATE) AS HOURS_UNTIL,
    DATEDIFF('day', CURRENT_DATE(), MATCH_DATE::DATE) AS DAYS_UNTIL,
    TO_CHAR(MATCH_DATE, 'DY DD MON HH24:MI') AS MATCH_DATETIME_DISPLAY
FROM SILVER.MATCHES
WHERE STATUS IN ('SCHEDULED', 'TIMED')
  AND MATCH_DATE > CURRENT_TIMESTAMP()
ORDER BY MATCH_DATE;

-- Task 8: Refresh MATCH_PATTERNS
CREATE OR REPLACE TASK TASK_REFRESH_MATCH_PATTERNS
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.MATCH_PATTERNS
SELECT
    COMPETITION_CODE,
    DAY_OF_WEEK,
    MATCH_HOUR,
    COUNT(*) AS TOTAL_MATCHES,
    ROUND(AVG(HOME_SCORE + AWAY_SCORE), 2) AS AVG_TOTAL_GOALS,
    ROUND(AVG(HOME_SCORE), 2) AS AVG_HOME_GOALS,
    ROUND(AVG(AWAY_SCORE), 2) AS AVG_AWAY_GOALS,
    SUM(CASE WHEN MATCH_DURATION != 'REGULAR' THEN 1 ELSE 0 END) AS EXTRA_TIME_MATCHES,
    SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS HOME_WINS,
    SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS AWAY_WINS,
    SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS DRAWS
FROM SILVER.MATCHES
WHERE STATUS = 'FINISHED'
  AND DAY_OF_WEEK IS NOT NULL
  AND MATCH_HOUR IS NOT NULL
GROUP BY COMPETITION_CODE, DAY_OF_WEEK, MATCH_HOUR;

-- Task 9: Refresh REFEREE_STATS
CREATE OR REPLACE TASK TASK_REFRESH_REFEREE_STATS
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.REFEREE_STATS
SELECT
    REFEREE_NAME,
    REFEREE_NATIONALITY,
    REFEREE_ID,
    COUNT(*) AS MATCHES_REFEREED,
    COUNT(DISTINCT COMPETITION_CODE) AS COMPETITIONS,
    COUNT(DISTINCT SEASON_YEAR) AS SEASONS,
    ROUND(AVG(HOME_SCORE + AWAY_SCORE), 2) AS AVG_GOALS_PER_MATCH,
    SUM(CASE WHEN MATCH_DURATION != 'REGULAR' THEN 1 ELSE 0 END) AS EXTRA_TIME_MATCHES,
    ROUND(100.0 * SUM(CASE WHEN MATCH_DURATION != 'REGULAR' THEN 1 ELSE 0 END) / COUNT(*), 1) AS EXTRA_TIME_PCT
FROM SILVER.MATCHES
WHERE STATUS = 'FINISHED'
  AND REFEREE_NAME IS NOT NULL
GROUP BY REFEREE_NAME, REFEREE_NATIONALITY, REFEREE_ID
ORDER BY MATCHES_REFEREED DESC;

-- Task 10: Refresh GEOGRAPHIC_STATS
CREATE OR REPLACE TASK TASK_REFRESH_GEOGRAPHIC_STATS
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.GEOGRAPHIC_STATS
SELECT
    AREA_NAME,
    AREA_CODE,
    COUNT(DISTINCT COMPETITION_CODE) AS COMPETITIONS,
    COUNT(*) AS TOTAL_MATCHES,
    ROUND(AVG(HOME_SCORE + AWAY_SCORE), 2) AS AVG_GOALS_PER_MATCH,
    SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS HOME_WINS,
    SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS AWAY_WINS,
    SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS DRAWS,
    ROUND(100.0 * SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) / COUNT(*), 1) AS HOME_WIN_PCT
FROM SILVER.MATCHES
WHERE STATUS = 'FINISHED'
  AND AREA_NAME IS NOT NULL
GROUP BY AREA_NAME, AREA_CODE
ORDER BY TOTAL_MATCHES DESC;

-- ----------------------------------------
-- TASK 11: Refresh GOLD ODDS_ANALYSIS
-- ----------------------------------------
CREATE OR REPLACE TASK TASK_REFRESH_ODDS_ANALYSIS
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.ODDS_ANALYSIS
SELECT
    o.GAME_ID,
    o.COMPETITION_CODE,
    o.COMMENCE_TIME,
    o.HOME_TEAM,
    o.AWAY_TEAM,
    COUNT(DISTINCT o.BOOKMAKER_KEY) AS NB_BOOKMAKERS,
    ROUND(AVG(o.HOME_ODDS), 2) AS AVG_HOME_ODDS,
    ROUND(AVG(o.DRAW_ODDS), 2) AS AVG_DRAW_ODDS,
    ROUND(AVG(o.AWAY_ODDS), 2) AS AVG_AWAY_ODDS,
    MAX(o.HOME_ODDS) AS BEST_HOME_ODDS,
    MAX(o.DRAW_ODDS) AS BEST_DRAW_ODDS,
    MAX(o.AWAY_ODDS) AS BEST_AWAY_ODDS,
    ROUND(1 / AVG(o.HOME_ODDS) * 100, 1) AS IMPLIED_HOME_PROB,
    ROUND(1 / AVG(o.DRAW_ODDS) * 100, 1) AS IMPLIED_DRAW_PROB,
    ROUND(1 / AVG(o.AWAY_ODDS) * 100, 1) AS IMPLIED_AWAY_PROB,
    ROUND((1/AVG(o.HOME_ODDS) + 1/AVG(o.DRAW_ODDS) + 1/AVG(o.AWAY_ODDS) - 1) * 100, 2) AS BOOKMAKER_MARGIN_PCT,
    MAX(o.LAST_UPDATE) AS LAST_ODDS_UPDATE
FROM SILVER.ODDS o
GROUP BY o.GAME_ID, o.COMPETITION_CODE, o.COMMENCE_TIME, o.HOME_TEAM, o.AWAY_TEAM
ORDER BY o.COMMENCE_TIME DESC;

-- ----------------------------------------
-- Resume tasks (enable DAG)
-- ----------------------------------------
ALTER TASK TASK_FETCH_ODDS RESUME;
ALTER TASK TASK_MERGE_TO_SILVER RESUME;
ALTER TASK TASK_REFRESH_LEAGUE_STANDINGS RESUME;
ALTER TASK TASK_REFRESH_TOP_SCORERS RESUME;
ALTER TASK TASK_REFRESH_TEAM_STATS RESUME;
ALTER TASK TASK_REFRESH_RECENT_MATCHES RESUME;
ALTER TASK TASK_REFRESH_UPCOMING_FIXTURES RESUME;
ALTER TASK TASK_REFRESH_MATCH_PATTERNS RESUME;
ALTER TASK TASK_REFRESH_REFEREE_STATS RESUME;
ALTER TASK TASK_REFRESH_GEOGRAPHIC_STATS RESUME;
ALTER TASK TASK_REFRESH_ODDS_ANALYSIS RESUME;
ALTER TASK TASK_FETCH_ALL_LEAGUES RESUME;

-- ----------------------------------------
-- Verify DAG
-- ----------------------------------------
SHOW TASKS IN SCHEMA COMMON;

-- Manual execution for testing:
-- EXECUTE TASK TASK_FETCH_ALL_LEAGUES;
