-- ============================================
-- SNOWGOAL - Tasks (Orchestration DAG)
-- ============================================

USE ROLE SNOWGOAL_ROLE;
USE WAREHOUSE SNOWGOAL_WH_XS;
USE DATABASE SNOWGOAL_DB;
USE SCHEMA COMMON;

-- ----------------------------------------
-- TASK 1: Fetch all leagues from API
-- Runs 3x daily: 7h, 17h, 00h (Europe/Paris)
-- ----------------------------------------
CREATE OR REPLACE TASK TASK_FETCH_ALL_LEAGUES
    WAREHOUSE = SNOWGOAL_WH_XS
    SCHEDULE = 'USING CRON 0 7,17,0 * * * Europe/Paris'
    COMMENT = 'Fetch data for all 5 European leagues from football-data.org (7h, 17h, 00h)'
AS
CALL FETCH_ALL_LEAGUES();

-- ----------------------------------------
-- TASK 2: Merge to Silver
-- Runs after fetch completes
-- ----------------------------------------
CREATE OR REPLACE TASK TASK_MERGE_TO_SILVER
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_FETCH_ALL_LEAGUES
AS
BEGIN
    -- MERGE MATCHES
    MERGE INTO SILVER.MATCHES AS target
    USING (
        SELECT DISTINCT
            MATCH_ID, COMPETITION_CODE, SEASON_YEAR, MATCH_DATE, STATUS, MATCHDAY, STAGE,
            HOME_TEAM_ID, HOME_TEAM_NAME, HOME_TEAM_SHORT, HOME_TEAM_TLA,
            AWAY_TEAM_ID, AWAY_TEAM_NAME, AWAY_TEAM_SHORT, AWAY_TEAM_TLA,
            HOME_SCORE, AWAY_SCORE, HOME_SCORE_HT, AWAY_SCORE_HT,
            WINNER, REFEREE_NAME, LAST_UPDATED
        FROM STAGING.V_MATCHES
        QUALIFY ROW_NUMBER() OVER (PARTITION BY MATCH_ID ORDER BY LOADED_AT DESC) = 1
    ) AS source
    ON target.MATCH_ID = source.MATCH_ID
    WHEN MATCHED AND source.LAST_UPDATED > target.LAST_UPDATED THEN UPDATE SET
        COMPETITION_CODE = source.COMPETITION_CODE,
        SEASON_YEAR = source.SEASON_YEAR,
        MATCH_DATE = source.MATCH_DATE,
        STATUS = source.STATUS,
        MATCHDAY = source.MATCHDAY,
        STAGE = source.STAGE,
        HOME_TEAM_ID = source.HOME_TEAM_ID,
        HOME_TEAM_NAME = source.HOME_TEAM_NAME,
        HOME_TEAM_SHORT = source.HOME_TEAM_SHORT,
        HOME_TEAM_TLA = source.HOME_TEAM_TLA,
        AWAY_TEAM_ID = source.AWAY_TEAM_ID,
        AWAY_TEAM_NAME = source.AWAY_TEAM_NAME,
        AWAY_TEAM_SHORT = source.AWAY_TEAM_SHORT,
        AWAY_TEAM_TLA = source.AWAY_TEAM_TLA,
        HOME_SCORE = source.HOME_SCORE,
        AWAY_SCORE = source.AWAY_SCORE,
        HOME_SCORE_HT = source.HOME_SCORE_HT,
        AWAY_SCORE_HT = source.AWAY_SCORE_HT,
        WINNER = source.WINNER,
        REFEREE_NAME = source.REFEREE_NAME,
        LAST_UPDATED = source.LAST_UPDATED,
        _UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        MATCH_ID, COMPETITION_CODE, SEASON_YEAR, MATCH_DATE, STATUS, MATCHDAY, STAGE,
        HOME_TEAM_ID, HOME_TEAM_NAME, HOME_TEAM_SHORT, HOME_TEAM_TLA,
        AWAY_TEAM_ID, AWAY_TEAM_NAME, AWAY_TEAM_SHORT, AWAY_TEAM_TLA,
        HOME_SCORE, AWAY_SCORE, HOME_SCORE_HT, AWAY_SCORE_HT,
        WINNER, REFEREE_NAME, LAST_UPDATED
    ) VALUES (
        source.MATCH_ID, source.COMPETITION_CODE, source.SEASON_YEAR, source.MATCH_DATE,
        source.STATUS, source.MATCHDAY, source.STAGE,
        source.HOME_TEAM_ID, source.HOME_TEAM_NAME, source.HOME_TEAM_SHORT, source.HOME_TEAM_TLA,
        source.AWAY_TEAM_ID, source.AWAY_TEAM_NAME, source.AWAY_TEAM_SHORT, source.AWAY_TEAM_TLA,
        source.HOME_SCORE, source.AWAY_SCORE, source.HOME_SCORE_HT, source.AWAY_SCORE_HT,
        source.WINNER, source.REFEREE_NAME, source.LAST_UPDATED
    );

    -- MERGE STANDINGS
    MERGE INTO SILVER.STANDINGS AS target
    USING (
        SELECT DISTINCT
            TEAM_ID, COMPETITION_CODE, SEASON_YEAR, POSITION, TEAM_NAME, TEAM_SHORT,
            TEAM_TLA, TEAM_CREST, PLAYED, WON, DRAW, LOST, POINTS,
            GOALS_FOR, GOALS_AGAINST, GOAL_DIFF, FORM
        FROM STAGING.V_STANDINGS
        QUALIFY ROW_NUMBER() OVER (PARTITION BY TEAM_ID, COMPETITION_CODE, SEASON_YEAR ORDER BY LOADED_AT DESC) = 1
    ) AS source
    ON target.TEAM_ID = source.TEAM_ID
       AND target.COMPETITION_CODE = source.COMPETITION_CODE
       AND target.SEASON_YEAR = source.SEASON_YEAR
    WHEN MATCHED THEN UPDATE SET
        POSITION = source.POSITION,
        TEAM_NAME = source.TEAM_NAME,
        TEAM_SHORT = source.TEAM_SHORT,
        TEAM_TLA = source.TEAM_TLA,
        TEAM_CREST = source.TEAM_CREST,
        PLAYED = source.PLAYED,
        WON = source.WON,
        DRAW = source.DRAW,
        LOST = source.LOST,
        POINTS = source.POINTS,
        GOALS_FOR = source.GOALS_FOR,
        GOALS_AGAINST = source.GOALS_AGAINST,
        GOAL_DIFF = source.GOAL_DIFF,
        FORM = source.FORM,
        _UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        TEAM_ID, COMPETITION_CODE, SEASON_YEAR, POSITION, TEAM_NAME, TEAM_SHORT,
        TEAM_TLA, TEAM_CREST, PLAYED, WON, DRAW, LOST, POINTS,
        GOALS_FOR, GOALS_AGAINST, GOAL_DIFF, FORM
    ) VALUES (
        source.TEAM_ID, source.COMPETITION_CODE, source.SEASON_YEAR, source.POSITION,
        source.TEAM_NAME, source.TEAM_SHORT, source.TEAM_TLA, source.TEAM_CREST,
        source.PLAYED, source.WON, source.DRAW, source.LOST, source.POINTS,
        source.GOALS_FOR, source.GOALS_AGAINST, source.GOAL_DIFF, source.FORM
    );

    -- MERGE TEAMS
    MERGE INTO SILVER.TEAMS AS target
    USING (
        SELECT DISTINCT
            TEAM_ID, COMPETITION_CODE, TEAM_NAME, TEAM_SHORT, TEAM_TLA, TEAM_CREST,
            ADDRESS, WEBSITE, FOUNDED, CLUB_COLORS, VENUE,
            COACH_ID, COACH_NAME, COACH_NATIONALITY
        FROM STAGING.V_TEAMS
        QUALIFY ROW_NUMBER() OVER (PARTITION BY TEAM_ID ORDER BY LOADED_AT DESC) = 1
    ) AS source
    ON target.TEAM_ID = source.TEAM_ID
    WHEN MATCHED THEN UPDATE SET
        COMPETITION_CODE = source.COMPETITION_CODE,
        TEAM_NAME = source.TEAM_NAME,
        TEAM_SHORT = source.TEAM_SHORT,
        TEAM_TLA = source.TEAM_TLA,
        TEAM_CREST = source.TEAM_CREST,
        ADDRESS = source.ADDRESS,
        WEBSITE = source.WEBSITE,
        FOUNDED = source.FOUNDED,
        CLUB_COLORS = source.CLUB_COLORS,
        VENUE = source.VENUE,
        COACH_ID = source.COACH_ID,
        COACH_NAME = source.COACH_NAME,
        COACH_NATIONALITY = source.COACH_NATIONALITY,
        _UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        TEAM_ID, COMPETITION_CODE, TEAM_NAME, TEAM_SHORT, TEAM_TLA, TEAM_CREST,
        ADDRESS, WEBSITE, FOUNDED, CLUB_COLORS, VENUE,
        COACH_ID, COACH_NAME, COACH_NATIONALITY
    ) VALUES (
        source.TEAM_ID, source.COMPETITION_CODE, source.TEAM_NAME, source.TEAM_SHORT,
        source.TEAM_TLA, source.TEAM_CREST, source.ADDRESS, source.WEBSITE,
        source.FOUNDED, source.CLUB_COLORS, source.VENUE,
        source.COACH_ID, source.COACH_NAME, source.COACH_NATIONALITY
    );

    -- MERGE SCORERS
    MERGE INTO SILVER.SCORERS AS target
    USING (
        SELECT DISTINCT
            PLAYER_ID, COMPETITION_CODE, SEASON_YEAR, PLAYER_NAME, FIRST_NAME, LAST_NAME,
            NATIONALITY, POSITION, DATE_OF_BIRTH, TEAM_ID, TEAM_NAME, TEAM_SHORT,
            GOALS, ASSISTS, PENALTIES, PLAYED_MATCHES
        FROM STAGING.V_SCORERS
        QUALIFY ROW_NUMBER() OVER (PARTITION BY PLAYER_ID, COMPETITION_CODE, SEASON_YEAR ORDER BY LOADED_AT DESC) = 1
    ) AS source
    ON target.PLAYER_ID = source.PLAYER_ID
       AND target.COMPETITION_CODE = source.COMPETITION_CODE
       AND target.SEASON_YEAR = source.SEASON_YEAR
    WHEN MATCHED THEN UPDATE SET
        PLAYER_NAME = source.PLAYER_NAME,
        FIRST_NAME = source.FIRST_NAME,
        LAST_NAME = source.LAST_NAME,
        NATIONALITY = source.NATIONALITY,
        POSITION = source.POSITION,
        DATE_OF_BIRTH = source.DATE_OF_BIRTH,
        TEAM_ID = source.TEAM_ID,
        TEAM_NAME = source.TEAM_NAME,
        TEAM_SHORT = source.TEAM_SHORT,
        GOALS = source.GOALS,
        ASSISTS = source.ASSISTS,
        PENALTIES = source.PENALTIES,
        PLAYED_MATCHES = source.PLAYED_MATCHES,
        _UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        PLAYER_ID, COMPETITION_CODE, SEASON_YEAR, PLAYER_NAME, FIRST_NAME, LAST_NAME,
        NATIONALITY, POSITION, DATE_OF_BIRTH, TEAM_ID, TEAM_NAME, TEAM_SHORT,
        GOALS, ASSISTS, PENALTIES, PLAYED_MATCHES
    ) VALUES (
        source.PLAYER_ID, source.COMPETITION_CODE, source.SEASON_YEAR, source.PLAYER_NAME,
        source.FIRST_NAME, source.LAST_NAME, source.NATIONALITY, source.POSITION,
        source.DATE_OF_BIRTH, source.TEAM_ID, source.TEAM_NAME, source.TEAM_SHORT,
        source.GOALS, source.ASSISTS, source.PENALTIES, source.PLAYED_MATCHES
    );

    -- MERGE COMPETITIONS
    MERGE INTO SILVER.COMPETITIONS AS target
    USING (
        SELECT DISTINCT
            COMPETITION_CODE, COMPETITION_ID, COMPETITION_NAME, TYPE, EMBLEM,
            AREA_NAME, AREA_CODE, AREA_FLAG, CURRENT_SEASON_ID,
            SEASON_START, SEASON_END, CURRENT_MATCHDAY
        FROM STAGING.V_COMPETITIONS
        QUALIFY ROW_NUMBER() OVER (PARTITION BY COMPETITION_CODE ORDER BY LOADED_AT DESC) = 1
    ) AS source
    ON target.COMPETITION_CODE = source.COMPETITION_CODE
    WHEN MATCHED THEN UPDATE SET
        COMPETITION_ID = source.COMPETITION_ID,
        COMPETITION_NAME = source.COMPETITION_NAME,
        TYPE = source.TYPE,
        EMBLEM = source.EMBLEM,
        AREA_NAME = source.AREA_NAME,
        AREA_CODE = source.AREA_CODE,
        AREA_FLAG = source.AREA_FLAG,
        CURRENT_SEASON_ID = source.CURRENT_SEASON_ID,
        SEASON_START = source.SEASON_START,
        SEASON_END = source.SEASON_END,
        CURRENT_MATCHDAY = source.CURRENT_MATCHDAY,
        _UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        COMPETITION_CODE, COMPETITION_ID, COMPETITION_NAME, TYPE, EMBLEM,
        AREA_NAME, AREA_CODE, AREA_FLAG, CURRENT_SEASON_ID,
        SEASON_START, SEASON_END, CURRENT_MATCHDAY
    ) VALUES (
        source.COMPETITION_CODE, source.COMPETITION_ID, source.COMPETITION_NAME,
        source.TYPE, source.EMBLEM, source.AREA_NAME, source.AREA_CODE,
        source.AREA_FLAG, source.CURRENT_SEASON_ID, source.SEASON_START,
        source.SEASON_END, source.CURRENT_MATCHDAY
    );
END;

-- ----------------------------------------
-- TASK 3-7: Refresh GOLD tables after SILVER merge
-- ----------------------------------------

-- Task 3: Refresh LEAGUE_STANDINGS
CREATE OR REPLACE TASK TASK_REFRESH_LEAGUE_STANDINGS
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.LEAGUE_STANDINGS
SELECT
    COMPETITION_CODE,
    SEASON_YEAR,
    POSITION,
    TEAM_ID,
    TEAM_NAME,
    TEAM_TLA,
    TEAM_CREST,
    PLAYED,
    WON,
    DRAW,
    LOST,
    POINTS,
    GOALS_FOR,
    GOALS_AGAINST,
    GOAL_DIFF,
    FORM,
    ROUND(POINTS / NULLIF(PLAYED, 0), 2) AS POINTS_PER_GAME,
    ROUND(GOALS_FOR / NULLIF(PLAYED, 0), 2) AS GOALS_PER_GAME,
    ROUND(GOALS_AGAINST / NULLIF(PLAYED, 0), 2) AS GOALS_CONCEDED_PER_GAME,
    ROUND(WON * 100.0 / NULLIF(PLAYED, 0), 1) AS WIN_PERCENTAGE
FROM SILVER.STANDINGS;

-- Task 4: Refresh TOP_SCORERS
CREATE OR REPLACE TASK TASK_REFRESH_TOP_SCORERS
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.TOP_SCORERS
SELECT
    COMPETITION_CODE,
    SEASON_YEAR,
    PLAYER_ID,
    PLAYER_NAME,
    NATIONALITY,
    POSITION,
    DATE_OF_BIRTH,
    DATEDIFF('year', DATE_OF_BIRTH, CURRENT_DATE()) AS AGE,
    TEAM_ID,
    TEAM_NAME,
    TEAM_SHORT,
    GOALS,
    ASSISTS,
    PENALTIES,
    PLAYED_MATCHES,
    GOALS + COALESCE(ASSISTS, 0) AS GOAL_CONTRIBUTIONS,
    ROUND(GOALS / NULLIF(PLAYED_MATCHES, 0), 2) AS GOALS_PER_MATCH,
    ROUND((GOALS + COALESCE(ASSISTS, 0)) / NULLIF(PLAYED_MATCHES, 0), 2) AS CONTRIBUTIONS_PER_MATCH,
    RANK() OVER (PARTITION BY COMPETITION_CODE, SEASON_YEAR ORDER BY GOALS DESC) AS GOALS_RANK,
    RANK() OVER (PARTITION BY COMPETITION_CODE, SEASON_YEAR ORDER BY GOALS + COALESCE(ASSISTS, 0) DESC) AS CONTRIBUTIONS_RANK
FROM SILVER.SCORERS;

-- Task 5: Refresh TEAM_STATS
CREATE OR REPLACE TASK TASK_REFRESH_TEAM_STATS
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.TEAM_STATS
WITH home_stats AS (
    SELECT
        COMPETITION_CODE,
        SEASON_YEAR,
        HOME_TEAM_ID AS TEAM_ID,
        HOME_TEAM_NAME AS TEAM_NAME,
        COUNT(*) AS HOME_PLAYED,
        SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS HOME_WINS,
        SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS HOME_DRAWS,
        SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS HOME_LOSSES,
        SUM(HOME_SCORE) AS HOME_GOALS_FOR,
        SUM(AWAY_SCORE) AS HOME_GOALS_AGAINST
    FROM SILVER.MATCHES
    WHERE STATUS = 'FINISHED'
    GROUP BY COMPETITION_CODE, SEASON_YEAR, HOME_TEAM_ID, HOME_TEAM_NAME
),
away_stats AS (
    SELECT
        COMPETITION_CODE,
        SEASON_YEAR,
        AWAY_TEAM_ID AS TEAM_ID,
        AWAY_TEAM_NAME AS TEAM_NAME,
        COUNT(*) AS AWAY_PLAYED,
        SUM(CASE WHEN WINNER = 'AWAY_TEAM' THEN 1 ELSE 0 END) AS AWAY_WINS,
        SUM(CASE WHEN WINNER = 'DRAW' THEN 1 ELSE 0 END) AS AWAY_DRAWS,
        SUM(CASE WHEN WINNER = 'HOME_TEAM' THEN 1 ELSE 0 END) AS AWAY_LOSSES,
        SUM(AWAY_SCORE) AS AWAY_GOALS_FOR,
        SUM(HOME_SCORE) AS AWAY_GOALS_AGAINST
    FROM SILVER.MATCHES
    WHERE STATUS = 'FINISHED'
    GROUP BY COMPETITION_CODE, SEASON_YEAR, AWAY_TEAM_ID, AWAY_TEAM_NAME
)
SELECT
    COALESCE(h.COMPETITION_CODE, a.COMPETITION_CODE) AS COMPETITION_CODE,
    COALESCE(h.SEASON_YEAR, a.SEASON_YEAR) AS SEASON_YEAR,
    COALESCE(h.TEAM_ID, a.TEAM_ID) AS TEAM_ID,
    COALESCE(h.TEAM_NAME, a.TEAM_NAME) AS TEAM_NAME,
    COALESCE(h.HOME_PLAYED, 0) AS HOME_PLAYED,
    COALESCE(h.HOME_WINS, 0) AS HOME_WINS,
    COALESCE(h.HOME_DRAWS, 0) AS HOME_DRAWS,
    COALESCE(h.HOME_LOSSES, 0) AS HOME_LOSSES,
    COALESCE(h.HOME_GOALS_FOR, 0) AS HOME_GOALS_FOR,
    COALESCE(h.HOME_GOALS_AGAINST, 0) AS HOME_GOALS_AGAINST,
    COALESCE(a.AWAY_PLAYED, 0) AS AWAY_PLAYED,
    COALESCE(a.AWAY_WINS, 0) AS AWAY_WINS,
    COALESCE(a.AWAY_DRAWS, 0) AS AWAY_DRAWS,
    COALESCE(a.AWAY_LOSSES, 0) AS AWAY_LOSSES,
    COALESCE(a.AWAY_GOALS_FOR, 0) AS AWAY_GOALS_FOR,
    COALESCE(a.AWAY_GOALS_AGAINST, 0) AS AWAY_GOALS_AGAINST,
    COALESCE(h.HOME_PLAYED, 0) + COALESCE(a.AWAY_PLAYED, 0) AS TOTAL_PLAYED,
    COALESCE(h.HOME_WINS, 0) + COALESCE(a.AWAY_WINS, 0) AS TOTAL_WINS,
    COALESCE(h.HOME_GOALS_FOR, 0) + COALESCE(a.AWAY_GOALS_FOR, 0) AS TOTAL_GOALS_FOR,
    COALESCE(h.HOME_GOALS_AGAINST, 0) + COALESCE(a.AWAY_GOALS_AGAINST, 0) AS TOTAL_GOALS_AGAINST,
    ROUND((COALESCE(h.HOME_WINS, 0) * 3 + COALESCE(h.HOME_DRAWS, 0)) / NULLIF(COALESCE(h.HOME_PLAYED, 0), 0), 2) AS HOME_PPG,
    ROUND((COALESCE(a.AWAY_WINS, 0) * 3 + COALESCE(a.AWAY_DRAWS, 0)) / NULLIF(COALESCE(a.AWAY_PLAYED, 0), 0), 2) AS AWAY_PPG
FROM home_stats h
FULL OUTER JOIN away_stats a
    ON h.TEAM_ID = a.TEAM_ID
    AND h.COMPETITION_CODE = a.COMPETITION_CODE
    AND h.SEASON_YEAR = a.SEASON_YEAR;

-- Task 6: Refresh RECENT_MATCHES
CREATE OR REPLACE TASK TASK_REFRESH_RECENT_MATCHES
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.RECENT_MATCHES
SELECT
    MATCH_ID,
    COMPETITION_CODE,
    SEASON_YEAR,
    MATCH_DATE,
    STATUS,
    MATCHDAY,
    STAGE,
    HOME_TEAM_ID,
    HOME_TEAM_NAME,
    HOME_TEAM_TLA,
    AWAY_TEAM_ID,
    AWAY_TEAM_NAME,
    AWAY_TEAM_TLA,
    HOME_SCORE,
    AWAY_SCORE,
    HOME_SCORE_HT,
    AWAY_SCORE_HT,
    WINNER,
    REFEREE_NAME,
    HOME_SCORE || ' - ' || AWAY_SCORE AS SCORE_DISPLAY,
    CASE
        WHEN WINNER = 'HOME_TEAM' THEN HOME_TEAM_TLA || ' WIN'
        WHEN WINNER = 'AWAY_TEAM' THEN AWAY_TEAM_TLA || ' WIN'
        WHEN WINNER = 'DRAW' THEN 'DRAW'
        ELSE STATUS
    END AS RESULT_DISPLAY,
    DATEDIFF('day', MATCH_DATE, CURRENT_TIMESTAMP()) AS DAYS_AGO
FROM SILVER.MATCHES
WHERE MATCH_DATE >= DATEADD('day', -30, CURRENT_DATE())
   OR STATUS IN ('SCHEDULED', 'TIMED', 'IN_PLAY', 'PAUSED');

-- Task 7: Refresh UPCOMING_FIXTURES
CREATE OR REPLACE TASK TASK_REFRESH_UPCOMING_FIXTURES
    WAREHOUSE = SNOWGOAL_WH_XS
    AFTER TASK_MERGE_TO_SILVER
AS
INSERT OVERWRITE INTO GOLD.UPCOMING_FIXTURES
SELECT
    MATCH_ID,
    COMPETITION_CODE,
    SEASON_YEAR,
    MATCH_DATE,
    STATUS,
    MATCHDAY,
    HOME_TEAM_ID,
    HOME_TEAM_NAME,
    HOME_TEAM_TLA,
    AWAY_TEAM_ID,
    AWAY_TEAM_NAME,
    AWAY_TEAM_TLA,
    DATEDIFF('hour', CURRENT_TIMESTAMP(), MATCH_DATE) AS HOURS_UNTIL,
    DATEDIFF('day', CURRENT_DATE(), MATCH_DATE::DATE) AS DAYS_UNTIL,
    TO_CHAR(MATCH_DATE, 'DY DD MON HH24:MI') AS MATCH_DATETIME_DISPLAY
FROM SILVER.MATCHES
WHERE STATUS IN ('SCHEDULED', 'TIMED')
  AND MATCH_DATE > CURRENT_TIMESTAMP()
ORDER BY MATCH_DATE;

-- ----------------------------------------
-- Resume tasks (enable DAG)
-- ----------------------------------------
ALTER TASK TASK_MERGE_TO_SILVER RESUME;
ALTER TASK TASK_REFRESH_LEAGUE_STANDINGS RESUME;
ALTER TASK TASK_REFRESH_TOP_SCORERS RESUME;
ALTER TASK TASK_REFRESH_TEAM_STATS RESUME;
ALTER TASK TASK_REFRESH_RECENT_MATCHES RESUME;
ALTER TASK TASK_REFRESH_UPCOMING_FIXTURES RESUME;
ALTER TASK TASK_FETCH_ALL_LEAGUES RESUME;

-- ----------------------------------------
-- Verify DAG
-- ----------------------------------------
SHOW TASKS IN SCHEMA COMMON;

-- Manual execution for testing:
-- EXECUTE TASK TASK_FETCH_ALL_LEAGUES;
