-- ============================================
-- SNOWGOAL - Logging Table
-- ============================================

USE ROLE SNOWGOAL_ROLE;
USE WAREHOUSE SNOWGOAL_WH_XS;
USE DATABASE SNOWGOAL_DB;
USE SCHEMA COMMON;

CREATE OR REPLACE TABLE PIPELINE_LOGS (
    LOG_ID NUMBER AUTOINCREMENT,
    EVENT_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LEVEL VARCHAR(10),            -- 'INFO', 'WARNING', 'ERROR'
    COMPONENT_NAME VARCHAR(100),
    MESSAGE STRING,
    STACK_TRACE STRING,
    AFFECTED_ROWS INT,
    RAW_DATA VARIANT
);