-- ============================================
-- SNOWGOAL - Verify Tasks Configuration
-- ============================================
USE ROLE SNOWGOAL_ROLE;
USE DATABASE SNOWGOAL_DB;
USE SCHEMA COMMON;

-- 1. Show all tasks
SHOW TASKS IN SCHEMA COMMON;

-- 2. Check task status and schedule
SELECT
    NAME,
    STATE,
    SCHEDULE,
    WAREHOUSE,
    PREDECESSORS
FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(TASK_NAME => 'TASK_FETCH_ALL_LEAGUES', RECURSIVE => TRUE))
ORDER BY NAME;

-- 3. Check task hierarchy
SELECT
    NAME,
    STATE,
    CASE
        WHEN PREDECESSORS IS NULL THEN 'ROOT'
        ELSE 'CHILD'
    END AS TASK_TYPE
FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(TASK_NAME => 'TASK_FETCH_ALL_LEAGUES', RECURSIVE => TRUE))
ORDER BY
    CASE WHEN PREDECESSORS IS NULL THEN 0 ELSE 1 END,
    NAME;

-- 4. Check last execution history
SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    RETURN_VALUE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME LIKE 'TASK_%'
ORDER BY SCHEDULED_TIME DESC
LIMIT 20;

-- 5. Verify expected 10 tasks exist
SELECT
    '✓ Expected 10 tasks' AS CHECK_NAME,
    COUNT(*) AS ACTUAL_COUNT,
    CASE
        WHEN COUNT(*) = 10 THEN '✓ PASS'
        ELSE '✗ FAIL'
    END AS STATUS
FROM INFORMATION_SCHEMA.TASKS
WHERE TASK_SCHEMA = 'COMMON'
  AND TASK_NAME LIKE 'TASK_%';

-- 6. Verify all tasks are RESUMED (started)
SELECT
    '✓ All tasks resumed' AS CHECK_NAME,
    SUM(CASE WHEN STATE = 'started' THEN 1 ELSE 0 END) AS STARTED_COUNT,
    COUNT(*) AS TOTAL_COUNT,
    CASE
        WHEN SUM(CASE WHEN STATE = 'started' THEN 1 ELSE 0 END) = COUNT(*) THEN '✓ PASS'
        ELSE '✗ FAIL - Some tasks are suspended'
    END AS STATUS
FROM INFORMATION_SCHEMA.TASKS
WHERE TASK_SCHEMA = 'COMMON'
  AND TASK_NAME LIKE 'TASK_%';
