-- ============================================
-- SNOWGOAL - Silver Tables
-- ============================================

USE DATABASE SNOWGOAL_DB;
USE SCHEMA SILVER;

-- ----------------------------------------
-- MATCHES - Table des matchs
-- ----------------------------------------
CREATE OR REPLACE TABLE MATCHES (
    MATCH_ID INT PRIMARY KEY,
    COMPETITION_CODE VARCHAR(10),
    SEASON_YEAR INT,
    MATCH_DATE TIMESTAMP_NTZ,
    STATUS VARCHAR(20),
    MATCHDAY INT,
    STAGE VARCHAR(50),
    HOME_TEAM_ID INT,
    HOME_TEAM_NAME VARCHAR(100),
    HOME_TEAM_SHORT VARCHAR(50),
    HOME_TEAM_TLA VARCHAR(5),
    AWAY_TEAM_ID INT,
    AWAY_TEAM_NAME VARCHAR(100),
    AWAY_TEAM_SHORT VARCHAR(50),
    AWAY_TEAM_TLA VARCHAR(5),
    HOME_SCORE INT,
    AWAY_SCORE INT,
    HOME_SCORE_HT INT,
    AWAY_SCORE_HT INT,
    WINNER VARCHAR(20),
    REFEREE_NAME VARCHAR(100),
    LAST_UPDATED TIMESTAMP_NTZ,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ----------------------------------------
-- STANDINGS - Classements
-- ----------------------------------------
CREATE OR REPLACE TABLE STANDINGS (
    TEAM_ID INT,
    COMPETITION_CODE VARCHAR(10),
    SEASON_YEAR INT,
    POSITION INT,
    TEAM_NAME VARCHAR(100),
    TEAM_SHORT VARCHAR(50),
    TEAM_TLA VARCHAR(5),
    TEAM_CREST VARCHAR(500),
    PLAYED INT,
    WON INT,
    DRAW INT,
    LOST INT,
    POINTS INT,
    GOALS_FOR INT,
    GOALS_AGAINST INT,
    GOAL_DIFF INT,
    FORM VARCHAR(20),
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TEAM_ID, COMPETITION_CODE, SEASON_YEAR)
);

-- ----------------------------------------
-- TEAMS - Équipes
-- ----------------------------------------
CREATE OR REPLACE TABLE TEAMS (
    TEAM_ID INT PRIMARY KEY,
    COMPETITION_CODE VARCHAR(10),
    TEAM_NAME VARCHAR(100),
    TEAM_SHORT VARCHAR(50),
    TEAM_TLA VARCHAR(5),
    TEAM_CREST VARCHAR(500),
    ADDRESS VARCHAR(200),
    WEBSITE VARCHAR(200),
    FOUNDED INT,
    CLUB_COLORS VARCHAR(100),
    VENUE VARCHAR(100),
    COACH_ID INT,
    COACH_NAME VARCHAR(100),
    COACH_NATIONALITY VARCHAR(50),
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ----------------------------------------
-- SCORERS - Buteurs
-- ----------------------------------------
CREATE OR REPLACE TABLE SCORERS (
    PLAYER_ID INT,
    COMPETITION_CODE VARCHAR(10),
    SEASON_YEAR INT,
    PLAYER_NAME VARCHAR(100),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    NATIONALITY VARCHAR(50),
    POSITION VARCHAR(30),
    DATE_OF_BIRTH DATE,
    TEAM_ID INT,
    TEAM_NAME VARCHAR(100),
    TEAM_SHORT VARCHAR(50),
    GOALS INT,
    ASSISTS INT,
    PENALTIES INT,
    PLAYED_MATCHES INT,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PLAYER_ID, COMPETITION_CODE, SEASON_YEAR)
);

-- ----------------------------------------
-- COMPETITIONS - Compétitions
-- ----------------------------------------
CREATE OR REPLACE TABLE COMPETITIONS (
    COMPETITION_CODE VARCHAR(10) PRIMARY KEY,
    COMPETITION_ID INT,
    COMPETITION_NAME VARCHAR(100),
    TYPE VARCHAR(20),
    EMBLEM VARCHAR(500),
    AREA_NAME VARCHAR(50),
    AREA_CODE VARCHAR(10),
    AREA_FLAG VARCHAR(500),
    CURRENT_SEASON_ID INT,
    SEASON_START DATE,
    SEASON_END DATE,
    CURRENT_MATCHDAY INT,
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Verify
SHOW TABLES IN SCHEMA SILVER;
